### ISSUE TITLE
Space bar becomes almost non-existent when exporting the font

### ISSUE THREAD

**Issue by umaerkamal** [glyphr-studio/Glyphr-Studio-1#308] opened 2020-05-06 23:52 UTC
Hi there!
![Capture](https://user-images.githubusercontent.com/27553776/81239540-9b786a00-901e-11ea-9569-e1e28e8e9d71.PNG)

First of all, great job on creating such a useful tool to tweak already existing font. 
Coming to the issue I am facing. I edited a font called Londrina. All the edits went well and exported the font as otf. When I installed, the space bar becomes almost non-existent. Is there something I did wrong? How can I fix it? 
Please help me as soon as you can. 

Regards

**Comment by mattlag** [comment] 2020-05-07 00:14
Can you take a look at the space character?  Usually it defaults to auto-calculate width = false, so you can set a specific width.  But if you started from an existing font, maybe the space character was imported improperly!  If you can, send me the file you tried to import.

![image](https://user-images.githubusercontent.com/5897669/81240678-e9f51c80-8fbc-11ea-8bc1-946270ad8656.png)

**Comment by umaerkamal** [comment] 2020-05-07 16:38
Thank you so much for your prompt response. Here are the two files,
original and edited. P.S what is the ideal emu value to for space?

**Comment by mattlag** [comment] 2020-08-13 20:42
Hello!  I'm going through issues, and noticed this thread is unresolved.  I think the two attachments you talked about didn't come through from email to github comments.  Could you email them to me directly?  mail@glyphrstudio.com  Thanks!

**Comment by mattlag** [comment] 2020-08-13 22:11
Actually, I discovered the root cause of this issue, it's actually an Import OTF issue with opentype.js - you can read about it on the v1.13.11 release notes: http://help.glyphrstudio.com/overview_updates.html

Basically, imported fonts are not returning an Advance Width for any character.  Glyphr Studio uses "Auto calculate glyph width" in these cases as a fallback... so most glyphs seem okay.  The one glyph where Auto Calculate does not work is the Space character, which falls back to a width of 0.

When opentype.js fixes this bug, it will also be fixed in Glyphr Studio.  Until then, widths will have to be manually set.

**Closed by mattlag** 2020-08-13 22:11 UTC
