### ISSUE TITLE
Renaming fonts and export

### ISSUE THREAD

**Issue by serrgiofdezz** [glyphr-studio/Glyphr-Studio-1#342] opened 2023-02-18 08:45 UTC
Hi, when I rename a font, apparently it does not rename to the given name, giving other one not mentioned instead....
![1](https://user-images.githubusercontent.com/45104843/219850920-7cdf9df9-af8d-45be-86f9-6cfed885d705.PNG)
![2](https://user-images.githubusercontent.com/45104843/219850921-3d46e222-a268-455b-9297-7a102266a303.PNG)

As can be seen in the photos, the name would be "Adif Fago Consensed Medium":

![3](https://user-images.githubusercontent.com/45104843/219850946-b064c137-e875-4985-a854-1b5fa49673be.PNG)

When I export it to OTF, everything seems nice, but when opening the file... The real name given to that font (and how it will detected on every program) is "Adif Fago Consensed Regular".

![4](https://user-images.githubusercontent.com/45104843/219850966-2cfa9e40-95cb-4740-a12d-e0c5df46be24.PNG)

Why is this happening? I can't figure it out

Thanks
Sergio

**Comment by mattlag** [comment] 2023-02-18 17:56
Hi Sergio

I think this is expected behavior. Because it is very common for fonts to come in families (like Times Regular / Times Bold / Times Italic / Times Bold Italic) using just the Family Name for identificaiton usually is not enough. Many programs that read fonts merge the Family Name and the Style name.

Just to double check, I created a font with Glyphr Studio where the family name was "Sample Font Family Name" and the style name was "FONT-STYLE".  I used a tool called TTX to look at how the data was written to the OTF file itself:

This is the `name` table, where you can see a mix of separate and combined names:
![image](https://user-images.githubusercontent.com/5897669/219880792-bd2c2556-6343-423f-9bfd-5659e221211f.png)

This is the top of the `CFF` table, which also has some values:
![image](https://user-images.githubusercontent.com/5897669/219880856-c39ee804-abf0-4dd6-8080-e02d810b6a62.png)

but, like I mentioned, this is expected behavior. If you are using different programs (Like Microsoft Word vs. Adobe Illustrator vs. Something Else) each individual program will use this information differently, and display it differently.

I'm going to close this issue, just because I think it's expected behavior, plus it's outside of the control of Glyphr Studio. If you would like to continue digging into the wide world of font properties (which Glyphr Studio only scratches the surface of) then I'd recommend either opening fonts in Font Forge, or taking a closer look at TTX (which dumps all OTF data into an XML format which is easy to read): https://fonttools.readthedocs.io/en/latest/ttx.html

**Closed by mattlag** 2023-02-18 17:56 UTC

**Comment by serrgiofdezz** [comment] 2023-02-19 10:52
Thanks, Matt
Undertood!

**Comment by mattlag** [comment] 2023-02-20 19:23
Thank you for the feedback, though - it's always good to point out unexpected behavior.
