### ISSUE TITLE
I can't add glyphes ranges

### ISSUE THREAD

**Issue by xreider** [glyphr-studio/Glyphr-Studio-1#312] opened 2020-06-19 23:50 UTC
I make some variants of writting chinese symbols.
And I can't add symbols like this 𠄌
unicode is 0x2010C 
How to do that?

I am making one range for one symbols, because I needn't other symbols from a range
For example, 
range name:亅
begin: 0x4E85
end: 0x4E85

these symbols have the problem to add
 
𠄌
𡿨 
𠃋
𠃑

**Comment by mattlag** [comment] 2020-06-20 04:14
Hello!

Glyphr Studio only supports the Basic Multilingual Plane, code points below 0xFFFF.  So, trying to add 0x2010C will be impossible.

For your second question, having single-glyph glyph ranges is totally fine.  If a few glyphs are close together, you can have a glyph range that holds all of them... which is common in font design.  But if you need single-glyph ranges, that's fine too.

You mention 4 glyphs you have a problem adding... They look like they are above 0xFFFF, so Glyphr Studio will not work.  I recommend using FontForge, it's free and open source, and supports every feature of OTF fonts.

**Comment by xreider** [comment] 2020-06-20 04:46
I found some symbols like these

𠄌 =>㇙
𡿨 =>㇛
𠃋 =>㇜
𠃑 =>㇞
And that solved my problem

But I have got another problem. Ligatures is not work on website.

**Comment by mattlag** [comment] 2020-06-20 04:58
Could you tell me more about the Ligatures issue?  What sequence are you trying to use?  What isn't working?

**Comment by xreider** [comment] 2020-06-20 05:11
They all work on "Test Drive" but some of them work. some not on a website


`<div class="radicalContainer"><div class="uniqueWritingFont">㇐</div><div class="uniqueWritingFont">乛</div><div class="uniqueWritingFont">丨</div><div class="uniqueWritingFont">丨(needle)</div><div class="uniqueWritingFont">丶</div><div class="uniqueWritingFont">丶(long)</div><div class="uniqueWritingFont">丶(very-long)</div><div class="uniqueWritingFont">丶(left)</div><div class="uniqueWritingFont">丿</div><div class="uniqueWritingFont">丿(lying)</div><div class="uniqueWritingFont">㇀</div><div class="uniqueWritingFont">㇀(lying)</div><div class="uniqueWritingFont">亅</div><div class="uniqueWritingFont">㇙</div><div class="uniqueWritingFont">㇊</div><div class="uniqueWritingFont">フ</div><div class="uniqueWritingFont">㇜</div><div class="uniqueWritingFont">㇜(upward)</div><div class="uniqueWritingFont">ㄣ</div><div class="uniqueWritingFont">㇛</div><div class="uniqueWritingFont">㇏</div><div class="uniqueWritingFont">㇏(lying)</div><div class="uniqueWritingFont">㇕</div><div class="uniqueWritingFont">㇅</div><div class="uniqueWritingFont">㇎</div><div class="uniqueWritingFont">㇂</div><div class="uniqueWritingFont">㇂(lying)</div><div class="uniqueWritingFont">㇢</div><div class="uniqueWritingFont">㇆</div><div class="uniqueWritingFont">⺄</div><div class="uniqueWritingFont">㇗</div><div class="uniqueWritingFont">㇗(pressed-down)</div><div class="uniqueWritingFont">㇞</div><div class="uniqueWritingFont">㇞(tight)</div><div class="uniqueWritingFont">㇉</div><div class="uniqueWritingFont">㇄</div><div class="uniqueWritingFont">乚</div><div class="uniqueWritingFont">㇍</div><div class="uniqueWritingFont">乚(crooked)</div><div class="uniqueWritingFont">乙</div><div class="uniqueWritingFont">㇋</div><div class="uniqueWritingFont">㇌</div><div class="uniqueWritingFont">㇌(without-hook)</div><div class="uniqueWritingFont">㇡</div></div>`

㇐乛丨丨(needle)丶丶(long)丶(very-long)丶(left)丿丿(lying)㇀㇀(lying)亅㇙㇊フ㇜㇜(upward)ㄣ㇛㇏㇏(lying)㇕㇅㇎㇂㇂(lying)㇢㇆⺄㇗㇗(pressed-down)㇞㇞(tight)㇉㇄乚㇍乚(crooked)乙㇋㇌㇌(without-hook)㇡

project file https://yadi.sk/d/9kYyemSchDzkTg
otf https://yadi.sk/d/OJ55HkqjtAiuAQ

I noticed that in project file name like (lying) have different glyphhtmls
sometimes is
 "glyphhtml": "&#12736;&#40;&#108;&#121;&#105;&#110;&#103;&#41;",
or
"glyphhtml": "&#12738;&#40;&#108;&#121;&#105;&#110;&#103;&#41;",

**Comment by xreider** [comment] 2020-06-20 06:56
In one moment ligatures stopped to work at all

**Comment by Davequinnf** [comment] 2020-07-02 14:11
Hello @xreider 
I believe your problem with ligatures could be caused by using too complicated names for them. I created some to render my company logo in my font by typing &lt;MyLogo&gt; and it didn't work. Then changed it to simpler MyLogo and it did. Try to use something like "mysymbolNeedle", "mysymbolLong" etc. Basically more "machine friendly" names (no special chars, spaces, ...). I tried it on your font and it works fine. Wish you good luck.

**Comment by mattlag** [comment] 2020-08-13 20:34
I'm going to close this issue - let me know if you have any more questions around this!

**Closed by mattlag** 2020-08-13 20:34 UTC

**Comment by Translator5** [comment] 2020-11-18 13:29
Any chances to add [Gothic](https://en.wikipedia.org/wiki/Gothic_alphabet) Script?

**Comment by mattlag** [comment] 2020-11-18 17:11
It looks like the Gothic alphabet is not in the Unicode Basic Multilingual Plane (glyphs below U+FFFF) so Glyphr Studio will not have direct support for that.  You could design those glyphs and put them into some other code points, but depending on your use case that's not exactly recommended.  

Font Forge is free and supports all the code points you would need for characters above U+FFFF.
